### PR TITLE
Fix wrong search model namespace

### PR DESCRIPTION
**Pull request by ada99**

### CODE REVIEW

**Comment by mootensai** [comment]
sorry, i've fix that before you create pull request, could you help me with #14 ?

**Comment by ada99** [comment]
Hi! I think my way is better. Take a look at multiple CRUD generation. It does not work, because $generator->searchModelClass is always empty and conditions like 
if (!empty($generator->searchModelClass))
does not work properly

**Comment by mootensai** [comment]
which file & line do you mean?

**Comment by mootensai** [comment]
I use your way then..

**Pull request closed without merging**
