### PR TITLE
Fixed relation name issue on CRUD

### PR DESCRIPTION
**Pull request by almirb**
Hello, 

I fixed the relation name issue on CRUD when model has multiple relations to another model.

### CODE REVIEW

**Comment by almirb** [comment]
Sorry... I created this pull request by mistake.  Please ignore it.

**Comment by mootensai** [comment]
```
                                                                                  Is there an issue if there's multiple relation on 1 model??
```

**Comment by almirb** [comment]
Yes It has an issue.

If I have 1 table named 'complaint' and It relates twice with 'person' as 'personClaimant' and 'personClaimed', but the CRUD generates wrong code on index and view:

Complaint model (Its OK):

```
 * @property \app\models\Person $personClaimant
 * @property \app\models\Person $personClaimed
```

But the gridview columns are generated this way:

```
 $gridColumn = [,
        [
            'attribute' => 'person.name',  //should be personClaimant.name
            'label' => 'Claimant Person',
        ],
        [
            'attribute' => 'person.name',  //should be personClaimed.name
            'label' => 'Claimed Person',
        ],
    ];
```

The same happens in gridview's Select2 values field.
My last commit in this PR has the fix..... but by mistake I put all my changes into It.

Thanks for your very nice work. It inspired me to make my own modifications.

See u!

**Comment by mootensai** [comment]
What did you change at your repo? could you list all your changes? Is it working well? If so, maybe I could merge with your version..

**Comment by almirb** [comment]
Hello Mr. @mootensai!

I did a lot of things here and will list them as soon I have time. Maybe you won't like all my changes, but  I'm sure you'll enjoy some.

**Pull request closed without merging**
